### ISSUE TITLE
Getting an error when right clicking in proxy

### ISSUE THREAD

**Issue by s0meguy1** [ricardojba/poi-slinger#2]
Hello,

This is based off your most recent release (1.8). I am using Burp Pro v2021.2 on Kali linux with jdk-14.0.2. This error occurs when right clicking on an item, the "Send to POI" is not present, as I believe the error stems from the menu options:

```
java.lang.NullPointerException
	at burp.BurpExtender.createMenuItems(BurpExtender.java:105)
	at burp.brr.a(Unknown Source)
	at burp.g5c.a(Unknown Source)
	at burp.ow.a(Unknown Source)
	at burp.ow.a(Unknown Source)
	at burp.ow.a(Unknown Source)
	at burp.f_0.a(Unknown Source)
	at burp.y0.b(Unknown Source)
	at burp.y0.a(Unknown Source)
	at burp.y0.mousePressed(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6633)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4545)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

The burp store version works - I just like having the most up to date extensions in my library

**Comment by ricardojba** [comment]
> Hello,
> 
> This is based off your most recent release (1.8). I am using Burp Pro v2021.2 on Kali linux with jdk-14.0.2. This error occurs when right clicking on an item, the "Send to POI" is not present, as I believe the error stems from the menu options:
> 
> ```
> java.lang.NullPointerException
> 	at burp.BurpExtender.createMenuItems(BurpExtender.java:105)
> 	at burp.brr.a(Unknown Source)
> 	at burp.g5c.a(Unknown Source)
> 	at burp.ow.a(Unknown Source)
> 	at burp.ow.a(Unknown Source)
> 	at burp.ow.a(Unknown Source)
> 	at burp.f_0.a(Unknown Source)
> 	at burp.y0.b(Unknown Source)
> 	at burp.y0.a(Unknown Source)
> 	at burp.y0.mousePressed(Unknown Source)
> 	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:288)
> 	at java.desktop/java.awt.AWTEventMulticaster.mousePressed(AWTEventMulticaster.java:287)
> 	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6633)
> 	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
> 	at java.desktop/java.awt.Component.processEvent(Component.java:6401)
> 	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
> 	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5012)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
> 	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4919)
> 	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4545)
> 	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4489)
> 	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
> 	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2764)
> 	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4844)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
> 	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
> 	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
> ```
> 
> The burp store version works - I just like having the most up to date extensions in my library

Hi,
Thank you for spotting and reporting the issue. Should be fixed on this new release.
Best,
RA

**Comment by s0meguy1** [comment]
Works! I am closing the issue now!
